spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bus_management_tool
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bus_management_tool

application:
  security:
    jwt:
      secret-key: cyKiCWf0E+gMexgr+jM/DHBYrxiDVsey4UzMVTS2dWVmouQVBNFcHnrhaeNnHvNK
      expiration: 8640000000 # a day
      refresh-token:
        expiration: 60480000000 # 7 days

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /v3/swagger-ui.html
