package com.snob.busmanagmenttool.model.entity.machinery;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum BusParts {
    ENGINE("Engine"),
    TRANSMISSION("Transmission"),
    WHEELS("Wheels"),
    TIRES("Tires"),
    BRAKES("Brakes"),
    SUSPENSION("Suspension"),
    STEERING_SYSTEM("Steering system"),
    EXHAUST_SYSTEM("Exhaust system"),
    ELECTRICAL_SYSTEM("Electrical system"),
    FUEL_SYSTEM("Fuel system"),
    AIR_CONDITIONING("Air conditioning"),
    HEATING_SYSTEM("Heating system"),
    INTERIOR_SEATS("Interior seats"),
    EXTERIOR_BODY_PANELS("Exterior body panels"),
    DOORS("Doors"),
    WINDOWS("Windows"),
    LIGHTS("Lights"),
    MIRRORS("Mirrors"),
    AUDIO_SYSTEM("Audio system"),
    SAFETY_FEATURES("Safety features"),
    GPS_NAVIGATION("GPS navigation"),
    BATTERY("Battery"),
    ALTERNATOR("Alternator"),
    STARTER("Starter"),
    RADIATOR("Radiator"),
    COOLING_SYSTEM("Cooling system"),
    OIL_FILTER("Oil filter"),
    AIR_FILTER("Air filter"),
    FUEL_FILTER("Fuel filter"),
    SPARK_PLUGS("Spark plugs"),
    IGNITION_COIL("Ignition coil"),
    WIPER_BLADES("Wiper blades"),
    OXYGEN_SENSOR("Oxygen sensor"),
    CATALYTIC_CONVERTER("Catalytic converter"),
    DRIVE_BELT("Drive belt"),
    TIMING_BELT("Timing belt"),
    SHOCK_ABSORBERS("Shock absorbers"),
    STRUTS("Struts"),
    CV_JOINTS("Cv joints"),
    DRIVE_SHAFT("Drive shaft"),
    AXLES("Axles"),
    UPHOLSTERY("Upholstery"),
    FLOOR_MAT("Floor mat"),
    HEADLINER("Headliner"),
    SEAT_BELTS("Seat belts"),
    SUNROOF("Sunroof"),
    CUP_HOLDERS("Cup holders"),
    TRUNK_COMPARTMENT("Trunk compartment"),
    ENGINE_OIL("Engine oil"),
    COOLANT("Coolant"),
    TRANSMISSION_FLUID("Transmission fluid"),
    BRAKE_FLUID("Brake fluid"),
    POWER_STEERING_FLUID("Power steering fluid"),
    WINDSHIELD_WASHER_FLUID("Windshield washer fluid"),
    FUEL("Fuel"),
    ENGINE_COOLANT_HOSE("Engine coolant hose"),
    IGNITION_SWITCH("Ignition switch"),
    THERMOSTAT("Thermostat"),
    ALARM_SYSTEM("Alarm system"),
    SPARE_TIRE("Spare tire"),
    JACK_TOOLKIT("Jack toolkit"),
    EMERGENCY_FLARES("Emergency flares"),
    FIRST_AID_KIT("First aid kit");
    private final String displayName;
    @Override
    public String toString() {
        return displayName;
    }
}
